// Default permission set for each built-in role. Used as the baseline before
// any per-user / per-custom-role override is applied.

import type { UserRole } from '@/lib/db/prisma-types'
import { PERMISSIONS, PermissionKey } from './keys'

const ALL_PERMISSIONS = Object.values(PERMISSIONS) as PermissionKey[]

export const ROLE_DEFAULT_PERMISSIONS: Record<UserRole, PermissionKey[]> = {
  ADMIN: ALL_PERMISSIONS,
  MANAGER: [
    // Full HR + finance access for branch managers, no system-level
    PERMISSIONS.TRANSACTIONS_VIEW,
    PERMISSIONS.TRANSACTIONS_REVIEW,
    PERMISSIONS.PROFITS_VIEW,
    PERMISSIONS.EXPENSES_VIEW, PERMISSIONS.EXPENSES_CREATE, PERMISSIONS.EXPENSES_EDIT,
    PERMISSIONS.ACCOUNTS_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.EMPLOYEES_VIEW, PERMISSIONS.EMPLOYEES_CREATE, PERMISSIONS.EMPLOYEES_EDIT,
    PERMISSIONS.SHIFTS_CHECKIN, PERMISSIONS.SHIFTS_APPROVE_HANDOVER,
    PERMISSIONS.ATTENDANCE_VIEW_ALL,
    PERMISSIONS.SCHEDULE_VIEW, PERMISSIONS.SCHEDULE_EDIT,
    PERMISSIONS.PAYROLL_VIEW, PERMISSIONS.PAYROLL_ADJUST, PERMISSIONS.PAYROLL_PAY,
    PERMISSIONS.BONUSES_ADD,
  ],
  SUPERVISOR: [
    PERMISSIONS.TRANSACTIONS_VIEW, PERMISSIONS.TRANSACTIONS_EDIT, PERMISSIONS.TRANSACTIONS_REVIEW,
    PERMISSIONS.RECONCILIATION_UPLOAD,    // ← upload SC + platform files
    PERMISSIONS.RECONCILIATION_CONSOLID,
    PERMISSIONS.ACCOUNTS_VIEW, PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.SHIFTS_CHECKIN, PERMISSIONS.SHIFTS_APPROVE_HANDOVER,
    PERMISSIONS.ATTENDANCE_VIEW_ALL,
  ],
  ACCOUNT_MGR: [
    PERMISSIONS.TRANSACTIONS_VIEW, PERMISSIONS.TRANSACTIONS_EDIT, PERMISSIONS.TRANSACTIONS_REVIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.SHIFTS_CHECKIN,
  ],
  EMPLOYEE: [
    PERMISSIONS.SHIFTS_CHECKIN,
  ],
}
